name: React App CI/CD

on:
  push:
    branches:
      - main

jobs:
  debug-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Debug before checkout
        run: |
          echo "Working directory before checkout:"
          pwd
          echo "Directory contents before checkout:"
          ls -la
          echo "Environment variables:"
          env | sort

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for proper Git operations
          # Add explicit token for authentication
          token: ${{ github.token }}

      - name: Debug after checkout
        run: |
          echo "Working directory after checkout:"
          pwd
          echo "Directory contents after checkout:"
          ls -la
          echo "Git status:"
          git status || echo "Git status failed"
          echo "Git info:"
          git --version
          git config --list || echo "Git config failed"
          echo ".git directory:"
          ls -la .git || echo ".git directory not found"

  build-and-test:
    needs: debug-environment
    name: build-and-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x] # You can add more versions if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper Git operations
          token: ${{ github.token }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: deploy
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.CICD_TOKEN }}
          publish_dir: ./dist
